DecisionTree:
  max_features:
    - sqrt
    - log2

RandomForest:
  n_estimators:
    - 8
    - 16
    - 32

GradientBoosting:
  n_estimators:
    - 8
    - 16
    - 32

LinearRegression: {}

KNN: {}

XGB:
  n_estimators:
    - 8
    - 16
    - 32

CatBoosting:
  learning_rate:
    - 0.01
    - 0.05
    - 0.1

AdaBoostRegressor:
  n_estimators:
    - 8
    - 16
    - 32
